### ISSUE TITLE
Can this be disabled?

### ISSUE THREAD

**Issue by mattjcowan** [directus/docs#167]
I think the fact that you use telemetry in every install should be documented. Is this feature in the docs? Is there a way to turn it off?

**Comment by mattjcowan** [comment]
It'll come up most likely in security audits with businesses that require strict CSP rules and same-origin policies.

![Screenshot 2019-06-25 17 31 27](https://user-images.githubusercontent.com/1571516/60138203-13bf9f00-976f-11e9-974b-eccc2304f8d4.png)

So while CSP rules can be added, I know at least some of my clients will require turning this off (GDPR compliant or not).

As far as where to add this, maybe under "Supporting Directus" or in Concepts, and/or in the app/api configuration sections if you provide an easy-way to disable it. Maybe an explanation on the hashing algorithm too (per server, per user, per session) and that it's continuously sending a 'ping', not just on 'install', but as soon as you login and every page load thereafter.

**Comment by benhaynes** [comment]
Thanks @mattjcowan — that all makes sense, and we certainly want to make things as easy as possible for our corporate users.

I will recommend that we add back that configuration flag for toggling this feature, and when we do I will update the config docs. In the meantime, I'll use this ticket to remind me to add `Telemetry` to concepts.

**Comment by arboehme** [comment]
Hi,

since I had the same requirement to disable the use of the telemetry service because of corporate restrictions in the firewall, I've create two pull requests for both APP and API with new config options:

https://github.com/directus/api/pull/1420 -> API

=> New option `"useTelemetry" : true / false` in the `"settings" `area of the `api.php`

https://github.com/directus/app/pull/2199 -> APP

=> New option `"useTelemetry" : true / false` in the `config.js`

Best regards

**Comment by benhaynes** [comment]
@rijkvanzanten — can this be closed upon v8 release?

**Comment by rijkvanzanten** [comment]
We released v8 with this feature and added a note in the new api reference
