### ISSUE TITLE
VitePress live updates stopped working

### ISSUE THREAD

**Issue by erondpowell** [directus/docs#195]
Suddenly VitePress `pnpm run dev` is not hot-updating content changes... It was working fine earlier today.
I have to `ctrl + c` crash the server and start it again to see changes.... 
Can somebody update their main branch and see if this is happening for them too? or perhaps its "on my end"...🤔 
@directus/team

**Comment by licitdev** [comment]
Just gave it a quick test, the issue seems to only be affecting the landing `introduction.md` 🤔

**Comment by azrikahar** [comment]
I can confirm it only happens on `/getting-started/introduction.md`, is it the same for you @erondpowell?

It seems like VitePress' HMR (live update) checks whether the current browser URL matches the page's path. Specific code snippet from `vitepress/dist/client/app/router.js` file for reference:

```js
function shouldHotReload(payload) {
    const payloadPath = payload.path.replace(/(\bindex)?\.md$/, '');
    const locationPath = location.pathname.replace(/(\bindex)?\.html$/, '');
    return payloadPath === locationPath;
}
```

However since the current workaround in `/index.md` "redirects" without affecting the browser URL, they are now out-of-sync, so VitePress' interprets it as there's no need to live update.

Here's a quick screen capture to clarify why the browser URL needs to match for live update to work:

https://user-images.githubusercontent.com/42867097/198184020-761c6ab0-2fa9-4ac9-b6f6-a6a6dee3a1fe.mp4

That being said, this seems to be only a gotcha for `/getting-started/introduction.md`, so not sure do we want to patch anything or only keep a note on this interaction going forward. 

Technically we can add a meta tag (only in dev) such as `<meta http-equiv="refresh" content="5;url=/getting-started/introduction.md" />` on the root path, but not sure do we want to venture down that path (no pun intended).

**Comment by rijkvanzanten** [comment]
> Technically we can add a meta tag (only in dev) such as <meta http-equiv="refresh" content="5;url=/getting-started/introduction.md" /> on the root path, but not sure do we want to venture down that path (no pun intended).

I think none of this redirect business is required with:

https://github.com/directus/docs/blob/19ab6bc1017f7c51661ca160ed5bd0b98a48ab22/netlify.toml#L15-L20

**Comment by azrikahar** [comment]
> I think none of this redirect business is required with:
> 
> https://github.com/directus/docs/blob/19ab6bc1017f7c51661ca160ed5bd0b98a48ab22/netlify.toml#L15-L20

Yeah it's definitely not needed for production with netlify's redirect, which is why I mentioned "only in dev" in my suggestion 👍 Unless it should/will actually redirect in dev? I believe it doesn't as we're not using `netlify dev` in this repo from my understanding.

(tested with wrapping said logic in `import.meta.env.DEV` condition which does seem to work and it will not add it to production, but personally am also preferring not to add such hacky logic in favor of noting such caveat somewhere for contributors)

**Comment by rijkvanzanten** [comment]
Also down to just drop it for dev purposes, doesn't really do too much
