### ISSUE TITLE
Many To Any (additional infos)

### ISSUE THREAD

**Issue by dgram** [directus/docs#241]
Are there a little bit more infos about, how to setup many to any in directus?

see https://docs.directus.io/guides/relationships.html#many-to-any

**Comment by rijkvanzanten** [comment]
Do you have a specific use case you're trying to meet?

**Comment by dgram** [comment]
yes, i'm having the following use case:

I need to handle/manage marketing campaigns.
We have an Marketing Campaign Collection and an Marketing Action Collection.
- 1 Marketing Campaign can have - N Marketing Actions

**Our problem is the following:**
An Marketing action could be a
- Facebook Post
- Offline Post Release
- Newsletter

all of these actions have an field overlap (i.e. name, description, medias), but all of these actions has own fields. When i understand it right as described in the docs (many-to-any) it's exactly what i need.

**Comment by benhaynes** [comment]
Hey @dgram — you are correct, M2X would solve this... but there's another way too (depends on your preference and architecture needs):

You can use a M2O on a single _actions_ collection, and then create Conditional Fields to hide the fields that aren't relevant. I don't know the state of conditional fields off the top of my head, but I think this would require you to create a custom interface (eg radios or dropdown) to select the type, and then hide the fields (using CSS + selectors) you don't want shown on the page. It really depends on how many fields you have and how many overlap.

Yet another option would be to have the overlap fields on the related Action collection, and then allow the user to add the custom field data through something more "open", like a repeater or key-value interface.

Plenty of options... just depends on dev preference and/or project requirements. I'll close this for now since we don't have M2X and therefore don't have Docs for it.

**Comment by dgram** [comment]
Hey @benhaynes 

thanks for your input. I will take a look at the conditional fields.

thanks and regards
