### ISSUE TITLE
Docs: Adding Restack as a way to deploy Directus on Kubernetes

### ISSUE THREAD

**Issue by kuberaspeaking** [directus/docs#252]
This contribution will add [Restack](https://www.restack.io/) as a way to deploy Directus on k8s in your own AWS infrastructure.

I will be adding this under self-hosted/Installation next to [docker.md](https://github.com/directus/docs/blob/main/self-hosted/installation/docker.md)
I have gone through the contribution guide.
Do let me know if you have any preferences like screenshots or no screenshots.
The page will look something like [this](https://www.restack.io/docs/deploy-appsmith-on-kubernetes)

**Comment by erondpowell** [comment]
Howdy there @kuberaspeaking !
Just checked out restack and it sounds super cool.

So, we've actually trimmed the self-hosted guides within the official documentation from about 12+ down to just [Docker](https://docs.directus.io/self-hosted/docker-guide.html), our recommended choice. The issue is that it takes a lot of effort for engineering to keep up with all these deployment options. We'd rather officially introduce one single self-hosted experience that our engineers are all familiar with, than dozens and dozens. This decision was made pretty recently, and we're still working out some of the details.

@phazonoverload At this point, do we have another community outlet in the works for guides like this?

**Comment by phazonoverload** [comment]
Hey @kuberaspeaking - we likely won't add this to our own docs for the reasons @erondpowell mentioned. I'd welcome you to create your own tutorial on restack.io which we'll gladly share. If we end up with a big enough pool of them, we may link out to guides like yours from the docs in time.

**Comment by kuberaspeaking** [comment]
Hey @phazonoverload , [here's the doc](https://www.restack.io/docs/deploy-directus-on-kubernetes) hosted on restack.io. Feel free to share it internally.
