### ISSUE TITLE
last_access_on is not triggered, when call by api.

### ISSUE THREAD

**Issue by KULTI1995** [directus/docs#285]
![image](https://user-images.githubusercontent.com/14282128/73569903-a2b23980-446b-11ea-9238-62c2df21a538.png)

```
"last_access_on": "2019-11-26T01:14:34+00:00",
"last_page": "/thumper/users/2"
```

why this fields not triggered, when call by api?

It would be very useful when, for example, I create a website and want to show when the creator of e.g. the post, was last available.

**Comment by rijkvanzanten** [comment]
last access on / last page are the last time the user used the directus app, and what page they were on. That's system internals that have nothing to do with your end project. That's by design, and won't be changed as they're needed to make the app function properly.

You can always add a new field in any collection and store information related to your project in there 🙂

**Comment by KULTI1995** [comment]
So how do you add extra functionality to a user, e.g. last_active?

**Comment by KULTI1995** [comment]
Writing such things in the meta user?

**Comment by rijkvanzanten** [comment]
it totally depends on what you're trying to achieve in your end project. You could create a separate collection to keep track of user activity
