### ISSUE TITLE
Translations - copy from

### ISSUE THREAD

**Issue by tonxxd** [directus/docs#325]
Hi, thank you very much for this awesome CMS, it should deserve more stars!

I am exploring the translation interface which is great but I am wondering if is there an option to copy the default values into the translated field. 
Like a button to "copy values from.." that populate all fields of English translation getting values from the main item.

If it's not available, is it possible to customize the translation interface without breaking eventual future upgrades? It would be nice for me to be able to add custom functionalities like this I have described or automatic translation with an API (I know it's not a very good solution but they asked me about this feature)

Thank you in advance

Enrico

**Comment by rijkvanzanten** [comment]
I'm not sure what you mean by

> Like a button to "copy values from.." that populate all fields of English translation getting values from the main item.

If the value already exists in the main item, why would you want to copy them to the English translation? In that case, why wouldn't you use the main item instead of rely on the translation that holds the copy?

Or from the opposite perspective, if the value is going to be translated, why keep a copy on the main item?

Maybe I'm just misunderstanding what you're trying to achieve. What's the real life use case here? 🙂

**Comment by tonxxd** [comment]
I have been asked to implement the automatic translation of some fields so that one can simply fix some errors instead of writing the translation from scratch. To do that I need the prefilled values to send to the API and set back the translated version. 
Don't know if I explained me well.
Probably a quick fix is to just query the main item from within the edit view and populate the fields programmatically.

Enrico

**Comment by rijkvanzanten** [comment]
I don't think I fully understand what you're saying, but querying the main item instead sounds like the way to go to me 👍
