### ISSUE TITLE
Add install and update sections

### ISSUE THREAD

**Issue by benhaynes** [directus/docs#5]
@rijkvanzanten 🔔 

https://docs.directus.io/app/admin-guide/#installation
https://docs.directus.io/app/admin-guide/#updating

**Comment by rijkvanzanten** [comment]
Added (mostly) in 
https://github.com/directus/docs-v7/commit/3a0c9024bd279bf9e031c1dc88cb2f7316cc78ae

I do need to play around with Docker some more before I can write the install instructions for it

**Comment by tiptronic** [comment]
It seems there are a couple of more things missing in the docs. I installed directus 6 w/o any problems.
I tried to install directus 7, but couldn't get it to work at all.

Maybe you should mention somewhere, that the /admin moved to /public/admin, and how that differs from former installs. (It's a one-liner somewhere in the admin-guide)

Try to update from Directus6:
When I am setting up the config (why is this called api.php?) and go to /public/admin, I see the login-screen, but can't log in ('user inactive').

[2018-10-27 09:29:41] api[_].ERROR: exception 'Directus\Authentication\Exception\UserInactiveException' with message 'User inactive' in /Volumes/XXX/Sites/directus7/src/core/Directus/Authentication/Provider.php:605


Clean install Directus7:
-----------------------
When I install a fresh copy of directus7 (MAMP-Pro Mac, empty database) manually (following the admin-guide), I can login using admin@example.com, but then I get an server error:
[2018-10-27 09:56:14] api[_].ERROR: exception 'Directus\Database\Exception\ItemNotFoundException' with message 'Item not found' in /Volumes/ST5/Sites/directus2/src/core/Directus/Services/ItemsService.php:106

If you want a log, here it is: 
https://www.dropbox.com/s/petqumhigd400n8/error.2018-10-27.log?dl=0
If you need more info, just drop me a note.

(needless to say, it wiped out the user's of version 6, which is not really nice ;)) 

The docs were's much helpful, because it seems they unfortunately don't take into account a clean/fresh installation. Also I noted some more general errors:

Install:
git clone -b build-v7 https://github.com/directus/directus.git
Error: fatal: Remote branch build-v7 not found in upstream origin

404:
https://docs.directus.io/api/admin-guide/requirements.html
https://docs.directus.io/api/admin-guide/configure.html

EMPTY:
https://docs.directus.io/api/admin/configure-with-app.html

Cheers

andy

**Comment by benhaynes** [comment]
Thank you @tiptronic – this is super helpful. Here are some updates we just made relating to your specific comments:

1. Added a warning to the top of our [main install page](https://docs.directus.io/install.html) warning about upgrading from v6.
2. Added [additional setup instructions](https://docs.directus.io/install.html#configure) for setting the document root to `/public`
3. Fixed the [install branch command](https://docs.directus.io/install.html#install) (no more `build-v7`)
4. Fixed the 404s in the Docs (was using an old route)

I think the "Item Not Found" error you're seeing is because you need to set the document root to `/public`... but maybe you did that? There was also an `.htaccess` issue (apache only) with the combined build (`@directus/directus`) so we're fixing that now and pushing a new release in a few minutes.

**Comment by tiptronic** [comment]
hi @benhaynes : I am currently out of my office, but will check that out once I'm back (most likely 10.Nov.)

**Comment by rijkvanzanten** [comment]
The only thing missing still is installation info on the (new) Docker setup, for which I've created a new issue: https://github.com/directus/docs/issues/47
